# Generated by Django 2.0.2 on 2018-02-09 13:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Dogodek')),
                ('short_description', models.CharField(max_length=50, verbose_name='Kratek opis')),
                ('description', models.CharField(max_length=700, verbose_name='Opis')),
                ('date', models.DateField(verbose_name='Datum')),
                ('img', models.ImageField(upload_to='', verbose_name='Slika')),
                ('registrations', django.contrib.postgres.fields.jsonb.JSONField(default=None, verbose_name='Prijave')),
            ],
        ),
    ]
