# Generated by Django 2.0.2 on 2018-02-13 10:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180213_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registrations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Prijave'),
        ),
    ]
